/* ============================================================
   נתוני החופשה – קפריסין אוגוסט 2026
   כל המידע במקום אחד כדי שיהיה קל לעדכן.
   ============================================================ */

const TRIP = {
  title: "החופשה שלנו בקפריסין",
  subtitle: "לרנקה · אוגוסט 2026 · אגדה אחת גדולה של כולנו ✨",
  destination: { city: "לרנקה", country: "קפריסין", lat: 34.977897, lon: 33.690251 },
  origin: { city: "תל אביב", lat: 32.0853, lon: 34.7818 },

  // יעד הספירה לאחור – המראה ראשונה
  countdownTo: "2026-08-12T09:00:00+03:00",

  hotel: {
    name: "Lordos Beach Hotel & Spa",
    nameHe: "לורדוס ביץ' הוטל אנד ספא",
    stars: 4,
    address: "Dhekelia Road, 6305 לרנקה, קפריסין",
    lat: 34.977897, lon: 33.690251,
    checkIn: "12.08.2026 · 15:00",
    checkOut: "16.08.2026 · 12:00",
    nights: 4,
    board: "לינה וארוחת בוקר (מזנון)",
    website: "https://lordosbeach.com.cy/",
    videoUrl: "https://www.youtube.com/shorts/UZ3nwTTqv4w",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=34.977897,33.690251",
    blurb: "מלון 4 כוכבים על חוף מפרץ לרנקה, עם בריכות מדורגות, ג'קוזי, פארק מים קטן לילדים, מגרש משחקים, מועדון ילדים וחוף פרטי עם שמשיות ומגבות חינם. מושלם למשפחה עם תינוקות.",
    amenities: [
      { icon: "🏖️", text: "חוף פרטי עם שמשיות ומגבות חינם" },
      { icon: "🏊", text: "בריכות חיצוניות מדורגות + ג'קוזי" },
      { icon: "💦", text: "פארק מים קטן ובריכת פעוטות" },
      { icon: "🛝", text: "מגרש משחקים ומועדון ילדים" },
      { icon: "👶", text: "לול ותינוקייה, כיסאות אוכל לתינוק (לפי בקשה)" },
      { icon: "🍽️", text: "מסעדת מזנון, בר בריכה ובר חוף" },
      { icon: "💆", text: "ספא, סאונה, חדר כושר" },
      { icon: "🎭", text: "תוכנית בידור יומית" },
    ],
    images: [
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80",
    ],
  },

  flights: [
    {
      dir: "הלוך", emoji: "🛫", flightNo: "U8103", airline: "TUS Airways",
      date: "2026-08-12", depTime: "09:00", arrTime: "10:05",
      from: { code: "TLV", name: "תל אביב (נתב\"ג)", terminal: "טרמינל 3" },
      to: { code: "LCA", name: "לרנקה", terminal: "" },
      depISO: "2026-08-12T09:00:00+03:00",
      statusUrl: "https://www.flightradar24.com/data/flights/u8103",
    },
    {
      dir: "חזור", emoji: "🛬", flightNo: "U8106", airline: "TUS Airways",
      date: "2026-08-16", depTime: "15:10", arrTime: "16:10",
      from: { code: "LCA", name: "לרנקה", terminal: "" },
      to: { code: "TLV", name: "תל אביב (נתב\"ג)", terminal: "טרמינל 3" },
      depISO: "2026-08-16T15:10:00+03:00",
      statusUrl: "https://www.flightradar24.com/data/flights/u8106",
    },
  ],
  bookingRef: "51033904",

  // כללי כבודה של TUS Airways
  baggageRules: {
    checked: { weight: "20 ק\"ג", note: "מזוודה לבטן המטוס" },
    trolley: { weight: "8 ק\"ג", dims: "55×40×23 ס\"מ", note: "טרולי לתא העליון" },
    personal: { weight: "4 ק\"ג", dims: "40×30×18 ס\"מ", note: "תיק אישי מתחת למושב" },
    infant: { weight: "5 ק\"ג", dims: "40×20×25 ס\"מ", note: "תיק תינוק בתא" },
    stroller: "עגלה וכיסא בטיחות – צ'ק-אין חינם! מקפלים בעמדת הצ'ק-אין, נוסעים בבטן המטוס ומוחזרים בנחיתה.",
  },

  // נוסעים + כבודה + פרופיל אריזה
  passengers: [
    {
      id: "yaniv", name: "יניב", full: "GOLTSHIAN / YANIV", role: "אבא של המשפחה", emoji: "👨",
      type: "adult", group: "א", checked: true, trolley: true,
      color: "#0ea5e9",
      packTitle: "ארגון, מסמכים וקצת גאדג'טים",
      packing: [
        "דרכונים של כל המשפחה + צילומים בענן",
        "כרטיסי טיסה והזמנת מלון מודפסים",
        "מטען נייד + כבלים + מתאם (קפריסין = שקע בריטי G!)",
        "תרופות אישיות + קופסת עזרה ראשונה משפחתית",
        "משקפי שמש, כובע, קרם הגנה 50+",
        "5 חולצות, 3 מכנסיים קצרים, בגד ים, כפכפים",
        "מעט מזומן ביורו + כרטיס אשראי",
      ],
    },
    {
      id: "efrat", name: "אפרת", full: "BEN HAMO / EFRAT", role: "אמא של שון", emoji: "👩",
      type: "adult", group: "א", checked: true, trolley: true,
      color: "#f43f5e",
      packTitle: "אופנה לחוף ולערב",
      packing: [
        "2 בגדי ים + פראו/שמלת חוף",
        "שמלה אחת לערב יפה במסעדה",
        "כפכפים + סנדלים נוחים להליכה",
        "כובע רחב שוליים + משקפי שמש",
        "קרם הגנה, אפטר-סאן, קרם לחות",
        "תיק חוף + בקבוק מים רב-פעמי",
        "תיק קוסמטיקה (מתחת ל-100 מ\"ל בטרולי)",
      ],
    },
    {
      id: "sean", name: "שון", full: "GOLTSHIAN / SEAN", role: "הילד", emoji: "🧒",
      type: "child", group: "א", checked: false, trolley: true,
      color: "#22c55e",
      alert: "לשון יש טרולי בלבד — אין מזוודה לבטן המטוס! אורזים אצל אבא/אמא.",
      packTitle: "כיף, משחקים וים",
      packing: [
        "טאבלט + אוזניות + משחקים לטיסה",
        "2 בגדי ים + מצופים / שרוולים",
        "צעצועי חוף (את/דלי)",
        "ספר/חוברת צביעה לרגעים שקטים",
        "בגדים קלים ל-4 ימים (אצל ההורים)",
        "כובע, משקפי שמש לילדים, קרם הגנה",
        "חטיף אהוב לטיסה",
      ],
    },
    {
      id: "talhaviv", name: "טל חביב", full: "GOLTSHIAN / TAL HAVIV", role: "אבא של אריאל", emoji: "👨",
      type: "adult", group: "ב", checked: true, trolley: true,
      color: "#8b5cf6",
      packTitle: "אבא של תינוק = לוגיסטיקה",
      packing: [
        "חיתולים לכל הטיול + מגבונים (קונים גם ב-Lidl/Metro)",
        "עגלת תינוק (צ'ק-אין חינם!) + כיסוי שמש",
        "מנשא/עטיפה לתינוק",
        "תרופות תינוק: אקמולי, משחת חיתולים",
        "בגד ים, כובע, קרם הגנה לתינוק (50+)",
        "בגדים אישיים ל-4 ימים + בגד ים",
        "מטען נייד לטלפון",
      ],
    },
    {
      id: "or", name: "אור", full: "GOLTSHIAN BEN HAMO / OR", role: "אמא של אריאל", emoji: "👩",
      type: "adult", group: "ב", checked: true, trolley: true,
      color: "#ec4899",
      packTitle: "אמא של תינוק = הכל מוכן",
      packing: [
        "בקבוקים, מזון תינוק/דייסה, כוס שתייה",
        "5 סטים בגדים לתינוק + פיג'מות",
        "בגדי ים לתינוק + חיתול שחייה",
        "שמיכת מעבר / מילוי שינה מוכר",
        "תיק החתלה מאובזר לטיסה",
        "בגדים אישיים + שמלת ערב",
        "מוצץ רזרבי + צעצוע הרגעה",
      ],
    },
    {
      id: "ariel", name: "אריאל", full: "GOLTSHIAN / ARIEL", role: "התינוק/ת של המשפחה", emoji: "👶",
      type: "infant", group: "ב", checked: false, trolley: false, stroller: true,
      color: "#fbbf24",
      alert: "אריאל טס/ה על הברכיים. מותרים תיק תינוק + עגלה בצ'ק-אין חינם 🎉",
      packTitle: "כוכב/ת החופשה",
      packing: [
        "עגלה קלה ומתקפלת (עולה בחינם!)",
        "מנשא ארגונומי לטיולים",
        "חיתולים + מגבונים בכמות",
        "מטרנה/מזון לפי הצורך",
        "בגדי ים + חיתול שחייה + כובע",
        "קרם הגנה לתינוקות",
        "צעצוע מוכר ומרגיע לטיסה",
      ],
    },
    {
      id: "michal", name: "מיכל", full: "GOLTSHIAN / MICHAL", role: "בני המשפחה", emoji: "👩",
      type: "adult", group: "ג", checked: true, trolley: true,
      color: "#14b8a6",
      packTitle: "קלילות וחופש",
      packing: [
        "בגדי ים + פראו לחוף",
        "שמלות קיץ קלילות לערב",
        "נעלי הליכה נוחות + כפכפים",
        "כובע, משקפי שמש, קרם הגנה",
        "תיק קוסמטיקה + תרופות אישיות",
        "ספר קריאה לחוף",
        "מתאם שקע בריטי (G)",
      ],
    },
    {
      id: "herzel", name: "הרצל", full: "GOLTSHIAN / HERZEL", role: "בני המשפחה", emoji: "👨",
      type: "adult", group: "ג", checked: true, trolley: true,
      color: "#f97316",
      packTitle: "רגוע ומוכן לכל",
      packing: [
        "בגדים קלילים ל-4 ימים + בגד ים",
        "כפכפים + נעליים נוחות",
        "כובע, משקפי שמש, קרם הגנה",
        "תרופות אישיות",
        "מטען נייד + מתאם בריטי (G)",
        "משקפת קטנה לאגם המלח 🦩",
        "מצב רוח טוב לחופשה!",
      ],
    },
  ],

  // טיפים שמשותפים לכולם
  universalTips: [
    { icon: "🔌", title: "שקע חשמל", text: "בקפריסין שקע בריטי (type G). אל תשכחו מתאם!" },
    { icon: "💧", title: "שתייה", text: "אוגוסט חם מאוד (32-33°). שתו הרבה מים והישארו בצל בשעות הצהריים." },
    { icon: "🧴", title: "הגנה מהשמש", text: "קרם 50+, כובעים ומשקפי שמש לכולם — במיוחד לילדים ולתינוק." },
    { icon: "💶", title: "מטבע", text: "בקפריסין משלמים ביורו (€). כדאי קצת מזומן + כרטיס." },
    { icon: "🚗", title: "תחבורה", text: "נוסעים בצד שמאל! שווה להזמין מונית/שכירת רכב מראש." },
    { icon: "📱", title: "אינטרנט", text: "חבילת eSIM לקפריסין או רואמינג — שימושי גם למפה החיה שלנו." },
  ],

  restaurants: [
    { name: "Pylion Fish Tavern", he: "פיליון – טברנת דגים", walk: "2 דק' הליכה", dist: 200,
      cuisine: "דגים ופירות ים טריים", price: "€€", emoji: "🐟",
      menu: ["דגים טריים על הגריל", "קלמארי", "סלט יווני", "מזה ים"],
      lat: 34.9765, lon: 33.6915, mapUrl: "https://www.google.com/maps/search/?api=1&query=Pylion+Fish+Tavern+Larnaca" },
    { name: "La Veranda", he: "לה ורנדה", walk: "2 דק' הליכה", dist: 200,
      cuisine: "ים תיכונית · אירופאית · ידידותי למשפחות", price: "€€", emoji: "🍝",
      menu: ["פסטות", "פיצות", "סטייקים", "תפריט ילדים"],
      lat: 34.9772, lon: 33.6890, mapUrl: "https://www.google.com/maps/search/?api=1&query=La+Veranda+Dhekelia+Larnaca" },
    { name: "Lysia Restaurant", he: "ליסיה", walk: "4 דק' הליכה", dist: 300,
      cuisine: "יוונית · קפריסאית · דגים", price: "€€", emoji: "🇬🇷",
      menu: ["סובלאקי", "מוסקה", "חלומי צלוי", "מזה קפריסאי"],
      lat: 34.9758, lon: 33.6925, mapUrl: "https://www.google.com/maps/search/?api=1&query=Lysia+Restaurant+Larnaca" },
    { name: "Ocean Basket Dhekelia", he: "אושן בסקט", walk: "7 דק' הליכה", dist: 550,
      cuisine: "פירות ים · רשת פופולרית · מחירים נוחים", price: "€€", emoji: "🦐",
      menu: ["פלטת פירות ים", "פיש אנד צ'יפס", "סושי", "תפריט ילדים"],
      lat: 34.9740, lon: 33.6950, mapUrl: "https://www.google.com/maps/search/?api=1&query=Ocean+Basket+Dhekelia" },
    { name: "Vlachos Tavern", he: "ולכוס – טברנה מסורתית", walk: "12 דק' הליכה", dist: 1100,
      cuisine: "מזה מסורתי · בשרים על הגריל", price: "€€", emoji: "🍢",
      menu: ["מזה ענק (20+ מנות)", "בשרים על הגריל", "נקניקיות כפריות", "יין מקומי"],
      lat: 34.9710, lon: 33.6990, mapUrl: "https://www.google.com/maps/search/?api=1&query=Vlachos+Tavern+Larnaca" },
    { name: "Psarolimano", he: "פסארולימנו – דגים", walk: "מונית קצרה", dist: 3000,
      cuisine: "דגים ומזה ים אותנטי", price: "€€€", emoji: "🐙",
      menu: ["תמנון על הגריל", "מזה דגים", "קלמארי ממולא", "שרימפס"],
      lat: 34.9180, lon: 33.6360, mapUrl: "https://www.google.com/maps/search/?api=1&query=Psarolimano+Larnaca" },
  ],

  attractions: [
    { name: "אגם המלח של לרנקה", emoji: "🦩", dist: "15 דק' נסיעה", stroller: true,
      text: "שביל שטוח וידידותי לעגלה, נוף קסום ומסגד האלה סולטן הסמוך. מושלם לטיול בוקר רגוע.",
      lat: 34.8870, lon: 33.6010, tag: "טבע · ידידותי לעגלה" },
    { name: "Camel Park – פארק הגמלים", emoji: "🐫", dist: "20 דק' נסיעה", stroller: true,
      text: "רכיבה על גמלים, האכלת בעלי חיים, בריכה, מגרש משחקים וקפה עם תפריט ילדים. יום כיף לכל המשפחה.",
      lat: 34.8030, lon: 33.4760, tag: "חיות · ילדים" },
    { name: "Water Planet Aqua Park", emoji: "💦", dist: "30 דק' נסיעה", stroller: false,
      text: "פארק מים עם מגלשות, בריכות ואזורי שכשוך — דרך מעולה להתקרר באוגוסט.",
      lat: 35.0380, lon: 34.0560, tag: "פארק מים · אקסטרים" },
    { name: "טיילת פיניקודס", emoji: "🌴", dist: "12 דק' נסיעה", stroller: true,
      text: "טיילת דקלים בלב לרנקה עם חוף, מגרשי משחקים, יריד ערב, גלידות ומסעדות. ערב מושלם.",
      lat: 34.9120, lon: 33.6370, tag: "טיילת · חוף · ערב" },
    { name: "חוף מקנזי", emoji: "🏖️", dist: "15 דק' נסיעה", stroller: true,
      text: "חוף משפחתי רחב עם מים רדודים, מגרשי משחקים ובתי קפה ליד שדה התעופה (כיף לראות מטוסים נוחתים!).",
      lat: 34.8870, lon: 33.6080, tag: "חוף · משפחות" },
    { name: "מצודת לרנקה", emoji: "🏰", dist: "13 דק' נסיעה", stroller: false,
      text: "מצודה היסטורית בקצה הטיילת עם נוף לים. שילוב נחמד של תרבות וטיול.",
      lat: 34.9100, lon: 33.6395, tag: "היסטוריה · נוף" },
  ],

  markets: [
    { name: "Lidl Oroklini", emoji: "🛒", text: "הכי קרוב וזול — מצרכים, חיתולים, פירות וירקות.", tag: "סופר · תינוקות",
      lat: 34.9870, lon: 33.6440, mapUrl: "https://www.google.com/maps/search/?api=1&query=Lidl+Oroklini" },
    { name: "Alphamega Hypermarket", emoji: "🏬", text: "היפר גדול עם מבחר ענק של מוצרי תינוק ומעדנייה.", tag: "היפר",
      lat: 34.9180, lon: 33.6230, mapUrl: "https://www.google.com/maps/search/?api=1&query=Alphamega+Larnaca" },
    { name: "Metro Supermarket", emoji: "🧺", text: "סופר גדול עם חיתולים, פינת החתלה ופירות טריים.", tag: "סופר · החתלה",
      lat: 34.9220, lon: 33.6280, mapUrl: "https://www.google.com/maps/search/?api=1&query=Metro+Supermarket+Larnaca" },
    { name: "בית מרקחת Pyla", emoji: "💊", text: "על כביש Dhekelia — תרופות תינוקות, מטרנה ומוצרי היגיינה.", tag: "בית מרקחת",
      lat: 34.9800, lon: 33.6850, mapUrl: "https://www.google.com/maps/search/?api=1&query=Pharmacy+Dhekelia+Road+Oroklini" },
  ],

  contact: {
    agency: "הדקה ה-90",
    person: "דיאנה",
    phone: "+972 52-652-7153",
    phoneClean: "+972526527153",
    office: "073-3909025",
    address: "המסגר 9, תל אביב",
  },

  // הגדרות מפה חיה
  liveMap: {
    broker: "wss://broker.emqx.io:8084/mqtt",
    room: "goltshian-cyprus-2026",  // אפשר לשנות לקוד פרטי
  },
};
