/* ============================================================
   ספר האגדות של המשפחה – חופשת קפריסין אוגוסט 2026
   כל המידע במקום אחד כדי שיהיה קל לעדכן.
   ============================================================ */

const TRIP = {
  title: "ספר האגדות של המשפחה",
  subtitle: "לרנקה · קפריסין · אוגוסט 2026 — אגדה אחת גדולה של כולנו ✨",
  destination: { city: "לרנקה", country: "קפריסין", lat: 34.977897, lon: 33.690251 },
  origin: { city: "תל אביב", lat: 32.0853, lon: 34.7818 },

  // יעד הספירה לאחור – המראה ראשונה
  countdownTo: "2026-08-12T09:00:00+03:00",

  hotel: {
    name: "Lordos Beach Hotel & Spa",
    nameHe: "לורדוס ביץ' הוטל אנד ספא",
    stars: 4,
    address: "Dhekelia Road, 6305 לרנקה, קפריסין",
    lat: 34.977897, lon: 33.690251,
    checkIn: "12.08.2026 · 15:00",
    checkOut: "16.08.2026 · 12:00",
    nights: 4,
    board: "לינה וארוחת בוקר (מזנון)",
    website: "https://lordosbeach.com.cy/",
    videoUrl: "https://www.youtube.com/shorts/UZ3nwTTqv4w",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=34.977897,33.690251",
    blurb: "טירת החוף שלנו: מלון 4 כוכבים על חוף החול של מפרץ לרנקה, עם בריכות נוצצות, ג'קוזי, פארק מים קטן לפעוטות, מגרש משחקים, מועדון ילדים, ספא וחמאם, מגרש פאדל וחוף פרטי עם שמשיות ומגבות חינם. ממש נבנתה למשפחה עם תינוקות.",
    amenities: [
      { icon: "🏖️", text: "חוף פרטי עם שמשיות ומגבות חינם" },
      { icon: "🏊", text: "בריכות חיצוניות + ג'קוזי + בריכה מקורה" },
      { icon: "💦", text: "פארק מים ובריכת פעוטות" },
      { icon: "🛝", text: "מגרש משחקים, מועדון ילדים ומיני-קלאב" },
      { icon: "👶", text: "לול ותינוקייה, כיסאות אוכל לתינוק (לפי בקשה)" },
      { icon: "🍽️", text: "מסעדת מזנון, בר בריכה ובר חוף" },
      { icon: "💆", text: "ספא, חמאם, סאונה וחדר כושר" },
      { icon: "🎾", text: "מגרש פאדל וטניס" },
      { icon: "🎭", text: "תוכנית בידור יומית" },
      { icon: "🅿️", text: "חניה חינם + Wi-Fi חינם" },
    ],
    // תמונות אמיתיות מהמלון (קבצים מקומיים)
    images: [
      { src: "hotel-aerial.jpg", cap: "מבט-על על טירת החוף 🐚" },
      { src: "hotel-pool.jpg", cap: "הבריכה הראשית והדקלים" },
      { src: "hotel-grounds.jpg", cap: "בריכת השחייה הגדולה" },
      { src: "hotel-kids-splash.jpg", cap: "פארק המים לפעוטות 🦆" },
      { src: "hotel-kids-play.jpg", cap: "פינת המשחקים הרטובה" },
      { src: "hotel-restaurant.jpg", cap: "מסעדה עם נוף לים 🌊" },
      { src: "hotel-beach.jpg", cap: "החוף הפרטי שלנו" },
      { src: "hotel-room.jpg", cap: "החדר שלנו — נוף לים" },
    ],
  },

  flights: [
    {
      dir: "הלוך", emoji: "🛫", flightNo: "U8103", airline: "TUS Airways",
      date: "2026-08-12", depTime: "09:00", arrTime: "10:05",
      from: { code: "TLV", name: "תל אביב (נתב\"ג)", terminal: "טרמינל 3" },
      to: { code: "LCA", name: "לרנקה", terminal: "" },
      depISO: "2026-08-12T09:00:00+03:00",
      statusUrl: "https://www.flightradar24.com/data/flights/u8103",
    },
    {
      dir: "חזור", emoji: "🛬", flightNo: "U8106", airline: "TUS Airways",
      date: "2026-08-16", depTime: "15:10", arrTime: "16:10",
      from: { code: "LCA", name: "לרנקה", terminal: "" },
      to: { code: "TLV", name: "תל אביב (נתב\"ג)", terminal: "טרמינל 3" },
      depISO: "2026-08-16T15:10:00+03:00",
      statusUrl: "https://www.flightradar24.com/data/flights/u8106",
    },
  ],
  bookingRef: "51033904",

  // כללי כבודה של TUS Airways — לכל מבוגר מגיע גם וגם וגם!
  baggageRules: {
    checked: { weight: "20 ק\"ג", dims: "80×50×28 ס\"מ", note: "מזוודה גדולה לבטן המטוס" },
    trolley: { weight: "8 ק\"ג", dims: "55×40×23 ס\"מ", note: "טרולי לתא העליון" },
    personal: { weight: "4 ק\"ג", dims: "40×30×18 ס\"מ", note: "תיק אישי מתחת למושב" },
    infant: { weight: "5 ק\"ג", dims: "40×20×25 ס\"מ", note: "תיק תינוק בתא" },
    stroller: "עגלה וכיסא בטיחות – צ'ק-אין חינם! מקפלים בעמדת הצ'ק-אין, נוסעים בבטן המטוס ומוחזרים מיד בנחיתה.",
    reassure: "כן! לכל מבוגר מותרים גם מזוודה גדולה (20 ק\"ג), גם טרולי (8 ק\"ג) וגם תיק אישי — לא צריך לבחור. כדאי רק לוודא מול דיאנה (הדקה ה-90) שהכבודה כלולה בחבילה שלנו.",
  },

  // נוסעים + כבודה + פרופיל אריזה
  passengers: [
    {
      id: "yaniv", name: "יניב", full: "GOLTSHIAN / YANIV", role: "ראש השיירה 👑", emoji: "👨",
      type: "adult", group: "א", checked: true, trolley: true,
      color: "#5b3fa6",
      packTitle: "ארגון, מסמכים וקצת קסמים",
      packing: [
        "דרכונים של כל המשפחה + צילומים בענן",
        "כרטיסי טיסה והזמנת מלון מודפסים (מס' 51033904)",
        "מטען נייד + כבלים + מתאם שקע בריטי (type G!)",
        "תרופות אישיות + ערכת עזרה ראשונה משפחתית (מד-חום, פלסטרים)",
        "משקפי שמש, כובע וקרם הגנה 50+",
        "מגבונים לחים + ג'ל אלכוהול לכל המשפחה",
        "5 חולצות, 3 מכנסיים קצרים, בגד ים, כפכפים",
        "מעט מזומן ביורו (€) + כרטיס אשראי",
      ],
    },
    {
      id: "efrat", name: "אפרת", full: "BEN HAMO / EFRAT", role: "החברה שמצטרפת לאגדה ✨", emoji: "👩",
      type: "adult", group: "א", checked: true, trolley: true,
      color: "#e85d8a",
      packTitle: "אופנה לחוף ולערב",
      packing: [
        "2 בגדי ים + פראו/שמלת חוף",
        "שמלה יפה לערב במסעדה",
        "כפכפים + סנדלים נוחים להליכה",
        "כובע רחב שוליים + משקפי שמש",
        "קרם הגנה 50+, אפטר-סאן וקרם לחות",
        "תיק חוף + בקבוק מים רב-פעמי",
        "תיק קוסמטיקה (נוזלים עד 100 מ\"ל בטרולי)",
        "מטען נייד + מתאם שקע בריטי (G)",
      ],
    },
    {
      id: "sean", name: "שון", full: "GOLTSHIAN / SEAN", role: "האביר הקטן 🗡️", emoji: "🧒",
      type: "child", group: "א", checked: false, trolley: true,
      color: "#4faf4a",
      alert: "לשון יש טרולי בלבד — אין מזוודה לבטן המטוס! אורזים אצל אבא/אמא.",
      packTitle: "כיף, משחקים וים",
      packing: [
        "טיטולים + מגבונים (שון עדיין לא גמול 💛)",
        "חיתול שחייה לבריכה ולים",
        "טאבלט + אוזניות + משחקים שקטים לטיסה",
        "2 בגדי ים + מצופים / שרוולי ציפה",
        "צעצועי חוף (את ודלי) 🪣",
        "כובע, משקפי שמש לילדים וקרם הגנה 50+",
        "בגדים קלים ל-4 ימים + 2 להחלפה (אצל ההורים)",
        "חטיף אהוב + כוס שתייה אטומה",
      ],
    },
    {
      id: "talhaviv", name: "טל חביב", full: "GOLTSHIAN / TAL HAVIV", role: "אבא של אריאל 🛡️", emoji: "👨",
      type: "adult", group: "ב", checked: true, trolley: true,
      color: "#3b2a73",
      packTitle: "אבא של תינוק = לוגיסטיקה",
      packing: [
        "טיטולים לכל הטיול + מגבונים (קונים גם ב-Lidl/Metro)",
        "עגלת תינוק (צ'ק-אין חינם!) + כיסוי שמש",
        "מנשא ארגונומי לתינוק",
        "משטח החתלה נייד + שקיות לחיתולים",
        "תרופות תינוק: אקמולי/נורופן תינוקות, מד-חום, משחת החתלה",
        "בגד ים, כובע וקרם הגנה לתינוק (50+)",
        "משקפי שמש, כובע וקרם הגנה לעצמך",
        "בגדים אישיים ל-4 ימים + מטען נייד",
      ],
    },
    {
      id: "or", name: "אור", full: "GOLTSHIAN BEN HAMO / OR", role: "אמא של אריאל 👸", emoji: "👩",
      type: "adult", group: "ב", checked: true, trolley: true,
      color: "#b8862a",
      packTitle: "אמא של תינוק = הכל מוכן",
      packing: [
        "בקבוקים, מטרנה/מזון תינוק, כוס שתייה",
        "5 סטים בגדים לתינוק + פיג'מות",
        "בגדי ים לתינוק + 2 חיתולי שחייה",
        "מגבונים, קרם החתלה ומשטח החתלה",
        "מוצצים (כמה רזרביים!) + צעצוע הרגעה",
        "שמיכת מעבר / חפץ שינה מוכר",
        "תיק החתלה מאובזר לטיסה (טיטולים, החלפה, מגבונים)",
        "בגדים אישיים, שמלת ערב, משקפי שמש",
      ],
    },
    {
      id: "ariel", name: "אריאל", full: "GOLTSHIAN / ARIEL", role: "כוכב/ת האגדה ⭐", emoji: "👶",
      type: "infant", group: "ב", checked: false, trolley: false, stroller: true,
      color: "#f6c453",
      alert: "אריאל טס/ה על הברכיים. מותרים תיק תינוק + עגלה בצ'ק-אין חינם 🎉",
      packTitle: "כוכב/ת החופשה",
      packing: [
        "עגלה קלה ומתקפלת (עולה בחינם!) ☁️",
        "מנשא ארגונומי לטיולים",
        "טיטולים + מגבונים בכמות גדולה",
        "מטרנה/מזון ובקבוקים",
        "2 בגדי ים + חיתולי שחייה + כובע רחב",
        "קרם הגנה לתינוקות + משקפי שמש לתינוק",
        "תרופות תינוק + מד-חום + משחת החתלה",
        "צעצוע מוכר ומרגיע + מוצץ לטיסה",
      ],
    },
    {
      id: "michal", name: "מיכל", full: "GOLTSHIAN / MICHAL", role: "בת המשפחה 💫", emoji: "👩",
      type: "adult", group: "ג", checked: true, trolley: true,
      color: "#2bb3c0",
      packTitle: "קלילות וחופש",
      packing: [
        "בגדי ים + פראו לחוף",
        "שמלות קיץ קלילות לערב",
        "נעלי הליכה נוחות + כפכפים",
        "כובע, משקפי שמש וקרם הגנה 50+",
        "מגבונים + ג'ל אלכוהול",
        "תיק קוסמטיקה + תרופות אישיות",
        "מתאם שקע בריטי (G) + מטען נייד",
        "ספר קריאה לחוף 📖",
      ],
    },
    {
      id: "herzel", name: "הרצל", full: "GOLTSHIAN / HERZEL", role: "בן המשפחה 🎩", emoji: "👨",
      type: "adult", group: "ג", checked: true, trolley: true,
      color: "#ff8a3d",
      packTitle: "רגוע ומוכן לכל",
      packing: [
        "בגדים קלילים ל-4 ימים + בגד ים",
        "כפכפים + נעליים נוחות",
        "כובע, משקפי שמש וקרם הגנה 50+",
        "תרופות אישיות + מגבונים",
        "מטען נייד + מתאם בריטי (G)",
        "משקפת קטנה לאגם המלח 🦩",
        "בקבוק מים רב-פעמי",
        "מצב רוח טוב לחופשה! ✨",
      ],
    },
  ],

  // טיפים שמשותפים לכולם
  universalTips: [
    { icon: "🔌", title: "שקע חשמל", text: "בקפריסין שקע בריטי (type G). אל תשכחו מתאם!" },
    { icon: "💧", title: "שתייה", text: "אוגוסט חם מאוד (32-33°). שתו הרבה מים והישארו בצל בצהריים." },
    { icon: "🧴", title: "הגנה מהשמש", text: "קרם 50+, כובעים ומשקפי שמש לכולם — במיוחד לילדים ולתינוק." },
    { icon: "👶", title: "תינוקות", text: "טיטולים ומגבונים אפשר לקנות ב-Lidl/Metro. קחו מלאי ליום הראשון." },
    { icon: "💶", title: "מטבע", text: "בקפריסין משלמים ביורו (€). כדאי קצת מזומן + כרטיס." },
    { icon: "🚕", title: "מוניות", text: "אין אובר בקפריסין — מורידים את Bolt (כמו אובר). נוסעים בצד שמאל!" },
    { icon: "📱", title: "אינטרנט", text: "חבילת eSIM לקפריסין או רואמינג — שימושי גם למפה החיה שלנו." },
    { icon: "🩴", title: "חוף", text: "המלון מספק מגבות חוף ושמשיות חינם — אפשר להשאיר בבית." },
  ],

  restaurants: [
    { name: "Pylion Fish Tavern", he: "פיליון – טברנת דגים", walk: "2 דק' הליכה", dist: 200,
      cuisine: "דגים ופירות ים טריים", price: "€€", emoji: "🐟",
      menu: ["דגים טריים על הגריל", "קלמארי", "סלט יווני", "מזה ים"],
      lat: 34.9765, lon: 33.6915, mapUrl: "https://www.google.com/maps/search/?api=1&query=Pylion+Fish+Tavern+Larnaca" },
    { name: "La Veranda", he: "לה ורנדה", walk: "2 דק' הליכה", dist: 200,
      cuisine: "ים תיכונית · אירופאית · ידידותי למשפחות", price: "€€", emoji: "🍝",
      menu: ["פסטות", "פיצות", "סטייקים", "תפריט ילדים"],
      lat: 34.9772, lon: 33.6890, mapUrl: "https://www.google.com/maps/search/?api=1&query=La+Veranda+Dhekelia+Larnaca" },
    { name: "Lysia Restaurant", he: "ליסיה", walk: "4 דק' הליכה", dist: 300,
      cuisine: "יוונית · קפריסאית · דגים", price: "€€", emoji: "🇬🇷",
      menu: ["סובלאקי", "מוסקה", "חלומי צלוי", "מזה קפריסאי"],
      lat: 34.9758, lon: 33.6925, mapUrl: "https://www.google.com/maps/search/?api=1&query=Lysia+Restaurant+Larnaca" },
    { name: "Ocean Basket Dhekelia", he: "אושן בסקט", walk: "7 דק' הליכה", dist: 550,
      cuisine: "פירות ים · רשת פופולרית · מחירים נוחים", price: "€€", emoji: "🦐",
      menu: ["פלטת פירות ים", "פיש אנד צ'יפס", "סושי", "תפריט ילדים"],
      lat: 34.9740, lon: 33.6950, mapUrl: "https://www.google.com/maps/search/?api=1&query=Ocean+Basket+Dhekelia" },
    { name: "Vlachos Tavern", he: "ולכוס – טברנה מסורתית", walk: "12 דק' הליכה", dist: 1100,
      cuisine: "מזה מסורתי · בשרים על הגריל", price: "€€", emoji: "🍢",
      menu: ["מזה ענק (20+ מנות)", "בשרים על הגריל", "נקניקיות כפריות", "יין מקומי"],
      lat: 34.9710, lon: 33.6990, mapUrl: "https://www.google.com/maps/search/?api=1&query=Vlachos+Tavern+Larnaca" },
    { name: "Psarolimano", he: "פסארולימנו – דגים", walk: "מונית קצרה", dist: 3000,
      cuisine: "דגים ומזה ים אותנטי", price: "€€€", emoji: "🐙",
      menu: ["תמנון על הגריל", "מזה דגים", "קלמארי ממולא", "שרימפס"],
      lat: 34.9180, lon: 33.6360, mapUrl: "https://www.google.com/maps/search/?api=1&query=Psarolimano+Larnaca" },
  ],

  attractions: [
    { name: "אגם המלח של לרנקה", emoji: "🦩", dist: "15 דק' נסיעה", stroller: true,
      text: "שביל שטוח וידידותי לעגלה, נוף קסום ומסגד האלה סולטן הסמוך. מושלם לטיול בוקר רגוע.",
      lat: 34.8870, lon: 33.6010, tag: "טבע · ידידותי לעגלה" },
    { name: "Camel Park – פארק הגמלים", emoji: "🐫", dist: "20 דק' נסיעה", stroller: true,
      text: "רכיבה על גמלים, האכלת בעלי חיים, בריכה, מגרש משחקים וקפה עם תפריט ילדים. יום כיף לכל המשפחה.",
      lat: 34.8030, lon: 33.4760, tag: "חיות · ילדים" },
    { name: "Water Planet Aqua Park", emoji: "💦", dist: "30 דק' נסיעה", stroller: false,
      text: "פארק מים עם מגלשות, בריכות ואזורי שכשוך — דרך מעולה להתקרר באוגוסט.",
      lat: 35.0380, lon: 34.0560, tag: "פארק מים · אקסטרים" },
    { name: "טיילת פיניקודס", emoji: "🌴", dist: "12 דק' נסיעה", stroller: true,
      text: "טיילת דקלים בלב לרנקה עם חוף, מגרשי משחקים, יריד ערב, גלידות ומסעדות. ערב מושלם.",
      lat: 34.9120, lon: 33.6370, tag: "טיילת · חוף · ערב" },
    { name: "חוף מקנזי", emoji: "🏖️", dist: "15 דק' נסיעה", stroller: true,
      text: "חוף משפחתי רחב עם מים רדודים, מגרשי משחקים ובתי קפה ליד שדה התעופה (כיף לראות מטוסים נוחתים!).",
      lat: 34.8870, lon: 33.6080, tag: "חוף · משפחות" },
    { name: "מצודת לרנקה", emoji: "🏰", dist: "13 דק' נסיעה", stroller: false,
      text: "מצודה היסטורית בקצה הטיילת עם נוף לים. שילוב נחמד של תרבות וטיול.",
      lat: 34.9100, lon: 33.6395, tag: "היסטוריה · נוף" },
  ],

  // שווקים, קניות וסופרים — עם מרחק מהמלון ואפשרות להזמין מונית
  markets: [
    { name: "שוק העירייה של לרנקה", en: "Larnaca Municipal Market", emoji: "🧺", kind: "שוק תוסס",
      tag: "מזכרות · חלומי · אוכל מקומי", taxi: "~15 דק' במונית", walk: "",
      text: "שוק מקורה תוסס בלב העיר: חלומי, תבלינים, פירות יבשים, תחרת לפקרה, מזכרות ומתוקים קפריסאיים. כיף להתמקח ולטעום!",
      lat: 34.9159, lon: 33.6339, mapUrl: "https://www.google.com/maps/search/?api=1&query=Larnaca+Municipal+Market" },
    { name: "רחוב הקניות ארמו", en: "Ermou Street", emoji: "🛍️", kind: "מדרחוב קניות",
      tag: "אופנה · בוטיקים · מזכרות", taxi: "~15 דק' במונית", walk: "",
      text: "רחוב הקניות המרכזי של לרנקה — אופנה, נעליים, תכשיטים, חנויות מזכרות ובתי קפה. מדרחוב נעים במיוחד לטיול ערב.",
      lat: 34.9168, lon: 33.6320, mapUrl: "https://www.google.com/maps/search/?api=1&query=Ermou+Street+Larnaca" },
    { name: "טיילת פיניקודס — דוכני ערב", en: "Finikoudes Promenade", emoji: "🌴", kind: "יריד חוף",
      tag: "יריד ערב · גלידות · מול הים", taxi: "~12 דק' במונית", walk: "",
      text: "בערב נפתחים דוכני אמנות ומזכרות לאורך טיילת הדקלים, עם גלידות, מסעדות ומגרשי משחקים מול הים. אווירה מושלמת.",
      lat: 34.9118, lon: 33.6360, mapUrl: "https://www.google.com/maps/search/?api=1&query=Finikoudes+Promenade+Larnaca" },
    { name: "קניון Metropolis Mall", en: "Metropolis Mall", emoji: "🏬", kind: "קניון גדול",
      tag: "100+ חנויות · ממוזג · פינת ילדים", taxi: "~13 דק' במונית", walk: "",
      text: "הקניון הגדול והחדש של לרנקה: Zara, Mango, M&S, אלקטרוניקה, סופר ענק, מסעדות, פינות משחק לילדים וקולנוע. בריחה מושלמת מהחום.",
      lat: 34.9226, lon: 33.6206, mapUrl: "https://www.google.com/maps/search/?api=1&query=Metropolis+Mall+Larnaca" },
    { name: "Lidl אורוקליני", en: "Lidl Oroklini", emoji: "🛒", kind: "סופר",
      tag: "הכי קרוב · חיתולים · מים", taxi: "~5 דק' במונית", walk: "~20 דק' הליכה",
      text: "הסופר הכי קרוב למלון — מצרכים, טיטולים, מגבונים, פירות וירקות במחיר נוח. מושלם ליום הראשון.",
      lat: 34.9870, lon: 33.6440, mapUrl: "https://www.google.com/maps/search/?api=1&query=Lidl+Oroklini" },
    { name: "Metro / Alphamega", en: "Metro & Alphamega", emoji: "🧴", kind: "היפרמרקט",
      tag: "מוצרי תינוק · החתלה", taxi: "~13 דק' במונית", walk: "",
      text: "היפרמרקטים גדולים עם מבחר ענק של מוצרי תינוק, מטרנה, טיטולים ופינת החתלה.",
      lat: 34.9200, lon: 33.6260, mapUrl: "https://www.google.com/maps/search/?api=1&query=Alphamega+Hypermarket+Larnaca" },
    { name: "בית מרקחת Pyla", en: "Pyla Pharmacy", emoji: "💊", kind: "בית מרקחת",
      tag: "תרופות תינוק", taxi: "~5 דק' במונית", walk: "",
      text: "על כביש Dhekelia — תרופות תינוקות, מטרנה ומוצרי היגיינה, ממש קרוב למלון.",
      lat: 34.9800, lon: 33.6850, mapUrl: "https://www.google.com/maps/search/?api=1&query=Pharmacy+Dhekelia+Road+Oroklini" },
  ],

  // תחבורה ומוניות — אין אובר בקפריסין!
  transport: {
    note: "בקפריסין אין אובר — האפליקציה הנפוצה היא Bolt (בדיוק כמו אובר). יש גם CABCY למוניות מקומיות. שימו לב: נוסעים בצד שמאל!",
    taxiUrl: "https://bolt.eu/en/cities/larnaca/",
    apps: [
      { name: "Bolt", emoji: "🚕", url: "https://bolt.eu/en/cities/larnaca/", primary: true },
      { name: "CABCY", emoji: "🚖", url: "https://cab.com.cy/", primary: false },
    ],
  },

  contact: {
    agency: "הדקה ה-90",
    person: "דיאנה",
    phone: "+972 52-652-7153",
    phoneClean: "+972526527153",
    office: "073-3909025",
    address: "המסגר 9, תל אביב",
  },

  // הגדרות מפה חיה
  liveMap: {
    broker: "wss://broker.emqx.io:8084/mqtt",
    room: "goltshian-cyprus-2026",  // אפשר לשנות לקוד פרטי
  },
};
